# Generated by Django 5.2.8 on 2026-02-09 11:50

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTaskGroupTemplate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, help_text='Description for this template (can use tokens like {SKU}). This will be appended to the site-wide description.')),
                ('tasks', wagtail.fields.StreamField([('task', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Task title (can use tokens like {SKU})', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels (e.g., sow, plant)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtask title (can use tokens)', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('labels', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Subtasks for this task', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('labels', 1), ('subtasks', 5)]], {})})),
            ],
            options={
                'verbose_name': 'Task Group Template',
                'verbose_name_plural': 'Task Group Templates',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_values', models.JSONField(default=dict, help_text='Token values used when creating this task group')),
                ('parent_task_id', models.CharField(help_text='Todoist parent task ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this task group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_groups', to='todosync.basetaskgrouptemplate')),
            ],
            options={
                'verbose_name': 'Task Group',
                'verbose_name_plural': 'Task Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(blank=True, help_text='Comma-separated list of tokens (e.g., SKU, VARIETYNAME)', max_length=500)),
                ('parent_task_title', models.CharField(blank=True, help_text='Title template for parent task (can use tokens like {SKU}). If empty, uses the template page title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description template for parent task (can use tokens like {SKU}). This will be prepended to the template description.')),
                ('todoist_project_id', models.CharField(blank=True, help_text='Todoist project ID where tasks should be created. Leave empty to create tasks in the inbox.', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Task Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='LabelActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section_id', models.CharField(blank=True, help_text='Todoist section ID to monitor for completed tasks with this label', max_length=100)),
                ('label', models.CharField(help_text="Label to match (e.g., 'harvest', 'plant')", max_length=100)),
                ('destination_section_id', models.CharField(help_text='Todoist section ID where completed tasks with this label should be moved', max_length=100)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_action_rules', to='todosync.tasksyncsettings')),
            ],
            options={
                'verbose_name': 'Label Action Rule',
                'verbose_name_plural': 'Label Action Rules',
            },
        ),
    ]
