# Generated by Django 5.2.8 on 2026-02-20 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "todo_id",
                    models.CharField(
                        blank=True, help_text="Task ID from external task management service", max_length=100
                    ),
                ),
                ("title", models.CharField(help_text="Task title as sent to external service", max_length=500)),
                (
                    "todo_section_id",
                    models.CharField(
                        blank=True,
                        help_text="Section ID from external service — used as column in kanban board",
                        max_length=50,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, help_text="Due date for this task", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task that must be completed before this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="todosync.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskSyncSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "default_project_id",
                    models.CharField(
                        blank=True,
                        help_text="Default project ID for task sync. Templates can override this per-template.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Sync Settings",
                "verbose_name_plural": "Task Sync Settings",
            },
        ),
        migrations.CreateModel(
            name="BaseParentTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todosync.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Task",
                "verbose_name_plural": "Parent Tasks",
                "ordering": ["-created_at"],
            },
            bases=("todosync.task",),
        ),
        migrations.CreateModel(
            name="BaseTaskGroupTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        help_text="Project ID for task sync. If empty, uses the default from Task Sync Settings.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description for this template (can use tokens). Appended to parent task description.",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Group Template",
                "verbose_name_plural": "Task Group Templates",
            },
        ),
        migrations.CreateModel(
            name="LabelActionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_section_id",
                    models.CharField(
                        blank=True,
                        help_text="Todoist section ID to monitor for completed tasks with this label",
                        max_length=100,
                    ),
                ),
                ("label", models.CharField(help_text="Label to match (e.g., 'harvest', 'plant')", max_length=100)),
                (
                    "destination_section_id",
                    models.CharField(
                        help_text="Todoist section ID where completed tasks with this label should be moved",
                        max_length=100,
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_action_rules",
                        to="todosync.tasksyncsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Label Action Rule",
                "verbose_name_plural": "Label Action Rules",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent task group this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_tasks",
                to="todosync.baseparenttask",
            ),
        ),
        migrations.AddField(
            model_name="baseparenttask",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to create this parent task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_tasks",
                to="todosync.basetaskgrouptemplate",
            ),
        ),
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                (
                    "task_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="todosync.task",
                    ),
                ),
                ("labels", models.CharField(blank=True, help_text="Labels (comma-separated)", max_length=500)),
                ("order", models.PositiveIntegerField(default=0, help_text="Sort order within the parent or template")),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tasks",
                        to="todosync.basetaskgrouptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Task",
                "verbose_name_plural": "Template Tasks",
                "ordering": ["order", "pk"],
            },
            bases=("todosync.task",),
        ),
        migrations.AddField(
            model_name="task",
            name="template_task",
            field=models.ForeignKey(
                blank=True,
                help_text="The template task this was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to="todosync.templatetask",
            ),
        ),
    ]
