# Generated by Django 5.2.8 on 2026-02-11 14:21

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_id', models.CharField(blank=True, help_text='Task ID from external task management service', max_length=100)),
                ('title', models.CharField(help_text='Task title as sent to external service', max_length=500)),
                ('todo_section_id', models.CharField(blank=True, help_text='Section ID from external service — used as column in kanban board', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, help_text='Scheduling/start date for this task', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Hard deadline for this task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_task', models.ForeignKey(blank=True, help_text='Parent task (null for top-level tasks under a BaseParentTask)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todosync.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_project_id', models.CharField(blank=True, help_text='Default project ID for task sync. Templates can override this per-template.', max_length=100)),
            ],
            options={
                'verbose_name': 'Task Sync Settings',
                'verbose_name_plural': 'Task Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='BaseTaskGroupTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, help_text='Project ID for task sync. If empty, uses the default from Task Sync Settings.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for this template (can use tokens). Appended to parent task description.')),
                ('tasks', django_jsonform.models.fields.JSONField(blank=True, default=list, help_text='Task definitions with token placeholders.')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Task Group Template',
                'verbose_name_plural': 'Task Group Templates',
            },
        ),
        migrations.CreateModel(
            name='LabelActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section_id', models.CharField(blank=True, help_text='Todoist section ID to monitor for completed tasks with this label', max_length=100)),
                ('label', models.CharField(help_text="Label to match (e.g., 'harvest', 'plant')", max_length=100)),
                ('destination_section_id', models.CharField(help_text='Todoist section ID where completed tasks with this label should be moved', max_length=100)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_action_rules', to='todosync.tasksyncsettings')),
            ],
            options={
                'verbose_name': 'Label Action Rule',
                'verbose_name_plural': 'Label Action Rules',
            },
        ),
        migrations.CreateModel(
            name='BaseParentTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todosync.task')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this parent task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tasks', to='todosync.basetaskgrouptemplate')),
            ],
            options={
                'verbose_name': 'Parent Task',
                'verbose_name_plural': 'Parent Tasks',
                'ordering': ['-created_at'],
            },
            bases=('todosync.task',),
        ),
    ]
