# Generated by Django 5.2.8 on 2026-02-09 23:43

import django.db.models.deletion
import modelcluster.fields
import todosync.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_id', models.CharField(blank=True, help_text='Todoist task ID', max_length=100)),
                ('title', models.CharField(help_text='Task title as sent to Todoist', max_length=500)),
                ('section', models.CharField(blank=True, help_text='Todoist section - used as column in kanban board', max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_task', models.ForeignKey(blank=True, help_text='Parent task (null for top-level tasks under a BaseParentTask)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todosync.task')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaseTaskGroupTemplate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('todoist_project_id', models.CharField(blank=True, help_text='Todoist project ID. If empty, uses the default from Task Sync Settings.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for this template (can use tokens). Appended to parent task description.')),
                ('tasks', wagtail.fields.StreamField([('task', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Task title (can use tokens like {SKU})', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels (e.g., sow, plant)', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subtask title (can use tokens)', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated labels', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('labels', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Subtasks for this task', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('labels', 1), ('subtasks', 5)]], {})})),
                ('task_type', models.ForeignKey(blank=True, help_text='The type of parent task to create from this template', limit_choices_to=todosync.models._parent_task_content_type_filter, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Task Group Template',
                'verbose_name_plural': 'Task Group Templates',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TaskSyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_project_id', models.CharField(blank=True, help_text='Default Todoist project ID. Templates can override this per-template.', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Task Sync Settings',
            },
        ),
        migrations.CreateModel(
            name='LabelActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section_id', models.CharField(blank=True, help_text='Todoist section ID to monitor for completed tasks with this label', max_length=100)),
                ('label', models.CharField(help_text="Label to match (e.g., 'harvest', 'plant')", max_length=100)),
                ('destination_section_id', models.CharField(help_text='Todoist section ID where completed tasks with this label should be moved', max_length=100)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_action_rules', to='todosync.tasksyncsettings')),
            ],
            options={
                'verbose_name': 'Label Action Rule',
                'verbose_name_plural': 'Label Action Rules',
            },
        ),
        migrations.CreateModel(
            name='BaseParentTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todosync.task')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this parent task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tasks', to='todosync.basetaskgrouptemplate')),
            ],
            options={
                'verbose_name': 'Parent Task',
                'verbose_name_plural': 'Parent Tasks',
                'ordering': ['-created_at'],
            },
            bases=('todosync.task',),
        ),
    ]
