# Generated by Django 5.2.8 on 2026-02-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todosync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksyncsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tasksyncsettings',
            name='parent_task_title',
        ),
        migrations.RemoveField(
            model_name='tasksyncsettings',
            name='tokens',
        ),
        migrations.AddField(
            model_name='basetaskgrouptemplate',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='The type of parent task to create from this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='basetaskgrouptemplate',
            name='todoist_project_id',
            field=models.CharField(blank=True, help_text='Todoist project ID. If empty, uses the default from Task Sync Settings.', max_length=100),
        ),
        migrations.AlterField(
            model_name='basetaskgrouptemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Description for this template (can use tokens). Appended to parent task description.'),
        ),
        migrations.AlterField(
            model_name='tasksyncsettings',
            name='todoist_project_id',
            field=models.CharField(blank=True, help_text='Default Todoist project ID. Templates can override this per-template.', max_length=100),
        ),
        migrations.CreateModel(
            name='BaseParentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_id', models.CharField(blank=True, help_text='Todoist task ID for the parent task', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this parent task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_tasks', to='todosync.basetaskgrouptemplate')),
            ],
            options={
                'verbose_name': 'Parent Task',
                'verbose_name_plural': 'Parent Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_id', models.CharField(blank=True, help_text='Todoist task ID', max_length=100)),
                ('title', models.CharField(help_text='Task title as sent to Todoist', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todosync.baseparenttask')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_id', models.CharField(blank=True, help_text='Todoist subtask ID', max_length=100)),
                ('title', models.CharField(help_text='Subtask title as sent to Todoist', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todosync.task')),
            ],
            options={
                'verbose_name': 'Sub Task',
                'verbose_name_plural': 'Sub Tasks',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
