# Generated by Django 6.0.2 on 2026-02-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetaskgrouptemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
