# Generated by Django 5.2.8 on 2026-02-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='section',
            new_name='todoist_section_id',
        ),
    ]
