# Generated by Django 5.2.8 on 2026-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, help_text='Hard deadline for this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='Scheduling/start date for this task', null=True),
        ),
    ]
