# Generated by Django 5.2.8 on 2026-02-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0002_task_due_date_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basetaskgrouptemplate',
            name='task_type',
        ),
    ]
