# Generated by Django 5.2.8 on 2026-02-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosync", "0002_remove_task_start_date_alter_task_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basetaskgrouptemplate",
            name="tasks",
        ),
        migrations.CreateModel(
            name="TemplateTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Task title (can use tokens like {sku})", max_length=500)),
                ("labels", models.CharField(blank=True, help_text="Labels (comma-separated)", max_length=500)),
                (
                    "due_date",
                    models.CharField(blank=True, help_text="Due date (YYYY-MM-DD, can use tokens)", max_length=100),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="Sort order within the parent or template")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent task (null for top-level tasks)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="todosync.templatetask",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Template this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_tasks",
                        to="todosync.basetaskgrouptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Task",
                "verbose_name_plural": "Template Tasks",
                "ordering": ["order", "pk"],
            },
        ),
    ]
