# Generated by Django 6.0.2 on 2026-02-24 07:20

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('todosync', '0002_basetaskgrouptemplate_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatetask',
            name='labels',
        ),
        migrations.AddField(
            model_name='basetaskgrouptemplate',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for this template', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags for this task', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
