# Generated by Django 5.2.8 on 2026-02-09 17:08

import django.db.models.deletion
import todosync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todosync', '0002_remove_tasksyncsettings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetaskgrouptemplate',
            name='task_type',
            field=models.ForeignKey(blank=True, help_text='The type of parent task to create from this template', limit_choices_to=todosync.models._parent_task_content_type_filter, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
