# Generated by Django 5.2.8 on 2026-02-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0003_alter_basetaskgrouptemplate_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseparenttask',
            name='completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='baseparenttask',
            name='section',
            field=models.CharField(blank=True, help_text='Todoist section - used as column in kanban board', max_length=50),
        ),
    ]
