# Generated by Django 6.0.2 on 2026-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0003_remove_templatetask_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Description for this task'),
        ),
    ]
