# Generated by Django 5.2.8 on 2026-02-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosync", "0003_remove_basetaskgrouptemplate_tasks_templatetask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetask",
            name="due_date",
            field=models.DateField(blank=True, help_text="Due date for this task", null=True),
        ),
    ]
