# Generated by Django 6.0.2 on 2026-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0004_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hide',
            field=models.BooleanField(default=True, help_text='If True, this task will be hidden in the external service until relevant'),
        ),
    ]
