# Generated by Django 5.2.8 on 2026-02-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosync", "0004_alter_templatetask_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatetask",
            name="parent",
        ),
        migrations.AddField(
            model_name="task",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                help_text="Task that must be completed before this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="todosync.task",
            ),
        ),
        migrations.AddField(
            model_name="templatetask",
            name="depends_on",
            field=models.ForeignKey(
                blank=True,
                help_text="Task that must be completed before this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependents",
                to="todosync.templatetask",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent task group this task belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_tasks",
                to="todosync.baseparenttask",
            ),
        ),
    ]
