# Generated by Django 6.0.2 on 2026-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todosync", "0006_remove_tasksyncsettings_default_project_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoistSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Human-readable slug (e.g. 'propagation'). Set by admin; preserved on sync.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "section_id",
                    models.CharField(
                        help_text="Todoist section ID", max_length=100, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name synced from Todoist API", max_length=255
                    ),
                ),
                (
                    "project_id",
                    models.CharField(
                        blank=True,
                        help_text="Todoist project ID this section belongs to",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Todoist Section",
                "verbose_name_plural": "Todoist Sections",
                "ordering": ["project_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaskRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        help_text="Task type label to scope rule to (e.g. 'crop'). Null matches all types.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rule_key",
                    models.CharField(
                        help_text="Namespaced key grouping related rules (e.g. 'crop_label_completion_section')",
                        max_length=100,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        help_text="Event that activates this rule (e.g. 'completed_task')",
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        help_text="Match condition in 'type:value' format (e.g. 'label:sow')",
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action to perform in 'type:value' format (e.g. 'section:propagation')",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Rule",
                "verbose_name_plural": "Task Rules",
                "ordering": ["rule_key", "trigger"],
                "indexes": [
                    models.Index(
                        fields=["rule_key", "trigger"],
                        name="todosync_ta_rule_ke_dd1108_idx",
                    )
                ],
            },
        ),
    ]
