# Generated by Django 6.0.2 on 2026-03-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0008_remove_taskrule_labelactionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoist_id', models.CharField(help_text='Todoist user ID', max_length=100, unique=True)),
                ('email', models.CharField(help_text='User email address', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text='User display name', max_length=255)),
            ],
            options={
                'verbose_name': 'Todoist User',
                'verbose_name_plural': 'Todoist Users',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Datetime the task was completed in Todoist', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed the task (from webhook initiator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='todosync.todoistuser'),
        ),
    ]
