# Generated by Django 6.0.2 on 2026-03-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosync', '0009_todoistuser_task_completed_at_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_created',
            field=models.BooleanField(default=False, help_text='True if this task was created directly by a user in Todoist (not by taskplanner)'),
        ),
    ]
